/*
 * Copyright 2026 Kazimierz Pogoda / Xemantic
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.xemantic.markanywhere.html.icons

import com.xemantic.markanywhere.SemanticEvent
import com.xemantic.markanywhere.classList
import com.xemantic.markanywhere.transform.MarkSelect

// Most common Material Icons / Symbols ligature names (with `_` already
// normalized to `-`) → the closest Unicode emoji. Variant suffixes are NOT
// listed: `canonicalIconName()` reduces `info-outline` → `info`,
// `star-border` → `star`, `thumb-up-alt` → `thumb-up`, etc. Curated against
// `material-icons-top500.json` (the 500 most popular icons); names with no
// reasonable emoji (`fingerprint`, `qr-code`, `tune`, `apps`, …) are left to
// the `:name:` fallback on purpose. Extend as new icons are encountered.
private val iconMap = mapOf(
    "accessibility" to "♿",
    "accessibility-new" to "♿",
    "account-balance" to "🏛️",
    "account-balance-wallet" to "👛",
    "account-box" to "👤",
    "account-circle" to "👤",
    "add" to "➕",
    "add-a-photo" to "📷",
    "add-box" to "➕",
    "add-circle" to "➕",
    "add-photo-alternate" to "🖼️",
    "add-shopping-cart" to "🛒",
    "add-task" to "✅",
    "alarm" to "⏰",
    "analytics" to "📊",
    "android" to "🤖",
    "announcement" to "📢",
    "apartment" to "🏢",
    "archive" to "📦",
    "arrow-back" to "⬅️",
    "arrow-circle-right" to "➡️",
    "arrow-circle-up" to "⬆️",
    "arrow-downward" to "⬇️",
    "arrow-drop-down" to "🔽",
    "arrow-drop-up" to "🔼",
    "arrow-forward" to "➡️",
    "arrow-left" to "◀️",
    "arrow-right" to "▶️",
    // `arrow-right-alt` is the long `→` arrow, not a variant of the small
    // `arrow-right` triangle pointer the canonicalizer would reduce it to.
    "arrow-right-alt" to "➡️",
    "arrow-upward" to "⬆️",
    "article" to "📄",
    "assessment" to "📊",
    "assignment" to "📋",
    "assignment-ind" to "📋",
    "assignment-turned-in" to "✅",
    "attach-file" to "📎",
    "attach-money" to "💲",
    "attachment" to "📎",
    "auto-awesome" to "✨",
    "auto-fix-high" to "🪄",
    "auto-stories" to "📖",
    "autorenew" to "🔄",
    "backspace" to "⌫",
    "badge" to "🪪",
    "bar-chart" to "📊",
    "battery-full" to "🔋",
    "block" to "🚫",
    "bolt" to "⚡",
    "book" to "📖",
    "bookmark" to "🔖",
    "bookmarks" to "🔖",
    "brush" to "🖌️",
    "bug-report" to "🐛",
    "build" to "🔧",
    "build-circle" to "🔧",
    "business" to "🏢",
    "business-center" to "💼",
    "cached" to "🔄",
    "cake" to "🎂",
    "calculate" to "🧮",
    "calendar-month" to "📅",
    "calendar-today" to "📅",
    "call" to "📞",
    "camera" to "📷",
    "campaign" to "📣",
    "cancel" to "❌",
    "card-giftcard" to "🎁",
    "celebration" to "🎉",
    "chat" to "💬",
    "chat-bubble" to "💬",
    "check" to "✅",
    "check-box" to "☑️",
    "check-box-outline-blank" to "☐",
    "check-circle" to "✅",
    "checklist" to "☑️",
    "chevron-left" to "◀️",
    "chevron-right" to "▶️",
    "circle" to "⚪",
    "clear" to "❌",
    "close" to "❌",
    "cloud" to "☁️",
    "code" to "💻",
    "collections" to "🖼️",
    "comment" to "💬",
    "compare-arrows" to "↔️",
    "computer" to "🖥️",
    "confirmation-number" to "🎟️",
    "construction" to "🛠️",
    "contact-mail" to "✉️",
    "contact-page" to "📇",
    "contact-phone" to "📞",
    "contact-support" to "❓",
    "contacts" to "📇",
    "content-copy" to "📋",
    "content-paste" to "📋",
    "copyright" to "©️",
    "corporate-fare" to "🏢",
    "create" to "✏️",
    "credit-card" to "💳",
    "credit-score" to "💳",
    "currency-exchange" to "💱",
    "dangerous" to "⚠️",
    "dark-mode" to "🌙",
    "dashboard" to "📊",
    "dashboard-customize" to "📊",
    "date-range" to "📅",
    "delete" to "🗑️",
    "delete-forever" to "🗑️",
    "description" to "📄",
    "desktop-windows" to "🖥️",
    "devices" to "💻",
    "directions-car" to "🚗",
    "directions-run" to "🏃",
    "directions-walk" to "🚶",
    "done" to "✅",
    "done-all" to "✅",
    "double-arrow" to "⏩",
    "download" to "⬇️",
    "download-for-offline" to "⬇️",
    "east" to "➡️",
    "edit" to "✏️",
    "edit-calendar" to "📅",
    "edit-note" to "📝",
    "email" to "✉️",
    "emoji-emotions" to "😀",
    "emoji-events" to "🏆",
    "emoji-objects" to "💡",
    "emoji-people" to "🙋",
    "engineering" to "👷",
    "equalizer" to "🎚️",
    "error" to "⚠️",
    "euro" to "💶",
    "euro-symbol" to "💶",
    "event" to "📅",
    "event-available" to "📅",
    "event-note" to "📅",
    "exit-to-app" to "🚪",
    "expand-less" to "🔼",
    "expand-more" to "🔽",
    "explore" to "🧭",
    "extension" to "🧩",
    "face" to "🙂",
    "fact-check" to "✅",
    "fast-forward" to "⏩",
    "favorite" to "❤️",
    "feed" to "📰",
    "feedback" to "💬",
    "file-copy" to "📋",
    "file-download" to "⬇️",
    "file-upload" to "⬆️",
    "filter-alt" to "🔻",
    "filter-list" to "🔻",
    "find-in-page" to "🔍",
    "fitness-center" to "🏋️",
    "flag" to "🚩",
    "flash-on" to "⚡",
    "flight" to "✈️",
    "flight-takeoff" to "🛫",
    "folder" to "📁",
    "folder-open" to "📂",
    "forum" to "💬",
    "gavel" to "🔨",
    "get-app" to "⬇️",
    "gps-fixed" to "🎯",
    "grade" to "⭐",
    "grading" to "📝",
    "group" to "👥",
    "group-add" to "👥",
    "group-work" to "👥",
    "groups" to "👥",
    "handshake" to "🤝",
    "handyman" to "🛠️",
    "headphones" to "🎧",
    "help" to "❓",
    "help-center" to "❓",
    "highlight-off" to "❌",
    "history" to "🕒",
    "history-edu" to "📜",
    "home" to "🏠",
    "hourglass-empty" to "⌛",
    "house" to "🏠",
    "https" to "🔒",
    "image" to "🖼️",
    "import-contacts" to "📖",
    "import-export" to "↕️",
    "inbox" to "📥",
    "info" to "ℹ️",
    "insert-drive-file" to "📄",
    "insights" to "📈",
    "inventory" to "📦",
    "inventory-2" to "📦",
    "ios-share" to "📤",
    "key" to "🔑",
    "keyboard" to "⌨️",
    "keyboard-arrow-down" to "🔽",
    "keyboard-arrow-left" to "◀️",
    "keyboard-arrow-right" to "▶️",
    "keyboard-arrow-up" to "🔼",
    "keyboard-backspace" to "⬅️",
    "label" to "🏷️",
    "language" to "🌐",
    "laptop" to "💻",
    "launch" to "↗️",
    "leaderboard" to "📊",
    "library-books" to "📚",
    "light-mode" to "☀️",
    "lightbulb" to "💡",
    "link" to "🔗",
    "list" to "☰",
    "live-help" to "❓",
    "live-tv" to "📺",
    "local-fire-department" to "🔥",
    "local-hospital" to "🏥",
    "local-library" to "📚",
    "local-mall" to "🛍️",
    "local-offer" to "🏷️",
    "local-shipping" to "🚚",
    "location-city" to "🏙️",
    "location-on" to "📍",
    "lock" to "🔒",
    "lock-open" to "🔓",
    "login" to "🚪",
    "logout" to "🚪",
    "loop" to "🔁",
    "lunch-dining" to "🍔",
    "mail" to "✉️",
    "manage-search" to "🔍",
    "map" to "🗺️",
    "medication" to "💊",
    "meeting-room" to "🚪",
    "menu" to "☰",
    "menu-book" to "📖",
    "message" to "💬",
    "mic" to "🎤",
    "mic-off" to "🔇",
    "military-tech" to "🎖️",
    "mode-edit" to "✏️",
    "monetization-on" to "💰",
    "more-horiz" to "⋯",
    "more-vert" to "⋮",
    "movie" to "🎬",
    "music-note" to "🎵",
    "navigate-before" to "◀️",
    "navigate-next" to "▶️",
    "new-releases" to "🆕",
    "newspaper" to "📰",
    "north" to "⬆️",
    "note-add" to "📝",
    "notification-important" to "🔔",
    "notifications" to "🔔",
    "notifications-active" to "🔔",
    "notifications-none" to "🔔",
    "notifications-off" to "🔕",
    "open-in-new" to "↗️",
    "paid" to "💰",
    "palette" to "🎨",
    "pan-tool" to "✋",
    "park" to "🌳",
    "password" to "🔑",
    "pause" to "⏸️",
    "payment" to "💳",
    "payments" to "💳",
    "pending" to "⏳",
    "pending-actions" to "⏳",
    "people" to "👥",
    "perm-identity" to "👤",
    "perm-media" to "🖼️",
    "person" to "👤",
    "person-add" to "👤",
    "pets" to "🐾",
    "phone" to "📞",
    "phone-android" to "📱",
    "phone-iphone" to "📱",
    "photo" to "🖼️",
    "photo-camera" to "📷",
    "picture-as-pdf" to "📄",
    "pin-drop" to "📍",
    "place" to "📍",
    "play-arrow" to "▶️",
    "play-circle" to "▶️",
    "print" to "🖨️",
    "priority-high" to "❗",
    "psychology" to "🧠",
    "public" to "🌐",
    "push-pin" to "📌",
    "query-builder" to "🕒",
    "query-stats" to "📊",
    "question-answer" to "💬",
    "question-mark" to "❓",
    "quiz" to "❓",
    "radio-button-checked" to "🔘",
    "radio-button-unchecked" to "⚪",
    "receipt" to "🧾",
    "receipt-long" to "🧾",
    "record-voice-over" to "🗣️",
    "redeem" to "🎁",
    "redo" to "↪️",
    "refresh" to "🔄",
    "remove" to "➖",
    "remove-circle" to "➖",
    "remove-red-eye" to "👁️",
    "reorder" to "☰",
    "replay" to "🔁",
    "reply" to "↩️",
    "report-problem" to "⚠️",
    "restart-alt" to "🔄",
    "restaurant" to "🍴",
    "restaurant-menu" to "🍴",
    "restore" to "🔄",
    "rocket" to "🚀",
    "rocket-launch" to "🚀",
    "room" to "📍",
    "save" to "💾",
    "savings" to "💰",
    "schedule" to "🕒",
    "school" to "🎓",
    "science" to "🔬",
    "search" to "🔍",
    "security" to "🛡️",
    "self-improvement" to "🧘",
    "sell" to "🏷️",
    "send" to "📤",
    "sentiment-dissatisfied" to "🙁",
    "sentiment-satisfied" to "🙂",
    "sentiment-very-dissatisfied" to "😞",
    "sentiment-very-satisfied" to "😄",
    "settings" to "⚙️",
    "share" to "🔗",
    "shield" to "🛡️",
    "shopping-bag" to "🛍️",
    "shopping-basket" to "🧺",
    "shopping-cart" to "🛒",
    "show-chart" to "📈",
    "signal-cellular-alt" to "📶",
    "skip-next" to "⏭️",
    "skip-previous" to "⏮️",
    "smart-display" to "📺",
    "smart-toy" to "🤖",
    "smartphone" to "📱",
    "sms" to "💬",
    "south" to "⬇️",
    "spa" to "🪷",
    "sports-esports" to "🎮",
    "star" to "⭐",
    "star-rate" to "⭐",
    "stars" to "⭐",
    "sticky-note-2" to "🗒️",
    "stop" to "⏹️",
    "storage" to "🗄️",
    "store" to "🏪",
    "storefront" to "🏪",
    "supervisor-account" to "👥",
    "support" to "🛟",
    "support-agent" to "🎧",
    "swap-horiz" to "↔️",
    "swap-vert" to "↕️",
    "sync" to "🔄",
    "task" to "📋",
    "task-alt" to "✅",
    "terminal" to "💻",
    "text-snippet" to "📄",
    "textsms" to "💬",
    "thermostat" to "🌡️",
    "thumb-down" to "👎",
    "thumb-up" to "👍",
    "thumb-up-off-alt" to "👍",
    "timeline" to "📈",
    "timer" to "⏱️",
    "tips-and-updates" to "💡",
    "today" to "📅",
    "touch-app" to "👆",
    "translate" to "🌐",
    "travel-explore" to "🌐",
    "trending-down" to "📉",
    "trending-flat" to "➡️",
    "trending-up" to "📈",
    "undo" to "↩️",
    "update" to "🔄",
    "upload" to "⬆️",
    "upload-file" to "⬆️",
    "verified" to "✅",
    "verified-user" to "🛡️",
    "videocam" to "🎥",
    "view-list" to "☰",
    "visibility" to "👁️",
    "visibility-off" to "🙈",
    "volume-off" to "🔇",
    "volume-up" to "🔊",
    "vpn-key" to "🔑",
    "warning" to "⚠️",
    "warning-amber" to "⚠️",
    "watch-later" to "🕒",
    "water-drop" to "💧",
    "wb-sunny" to "☀️",
    "west" to "⬅️",
    "wifi" to "📶",
    "work" to "💼",
    "workspace-premium" to "🏅",
    "zoom-in" to "🔍",
)

/**
 * Resolves [Material Icons / Symbols](https://fonts.google.com/icons) — a
 * *ligature* font: `<span class="material-icons">open_in_new</span>`. The glyph
 * name is the element's **text content**, not a class token, so the resolution
 * happens inside the [MarkTransform][com.xemantic.markanywhere.transform.MarkTransform],
 * where the buffered subtree (and therefore the text) is visible. A matched
 * element carrying no text replays verbatim.
 */
public val MaterialIconResolver: MarkSelect = { mark ->
    val isMaterial = mark.classList.any {
        it.startsWith("material-icons") || it.startsWith("material-symbols")
    }
    if (isMaterial) {
        { events ->
            val ligature = events
                .filterIsInstance<SemanticEvent.Text>()
                .joinToString("") { it.text }
                .trim()
            if (ligature.isNotEmpty()) {
                "icon" { +ligature.toIconToken() }
            } else {
                // no ligature text — not an icon carrier after all
                emit(events)
            }
        }
    } else null
}

// A recognized glyph resolves to its curated emoji (looked up raw, then after
// canonicalization), otherwise to a `:name:` hint so the label survives
// downstream. Material ligatures use `_` separators; normalized to the `-` the
// map uses.
private fun String.toIconToken(): String {
    val name = lowercase().replace('_', '-')
    return iconMap[name] ?: iconMap[name.canonicalIconName()] ?: ":$name:"
}

// Strips variant suffixes so `info-outline`, `star-border`, `delete-outlined`,
// `thumb-up-alt`, `arrow-back-ios` all reduce to their base name. Raw map
// lookup wins first, so names where the suffix is load-bearing (`filter-alt`,
// `task-alt`, `signal-cellular-alt`, …) just need their own entry.
private fun String.canonicalIconName(): String {
    var n = this
    for (suffix in VARIANT_SUFFIXES) {
        if (n.length > suffix.length && n.endsWith(suffix)) {
            n = n.removeSuffix(suffix)
            break
        }
    }
    return n
}

// `-ios-new` must precede `-ios` so the longer suffix wins.
private val VARIANT_SUFFIXES = listOf(
    "-outline", "-outlined", "-border", "-filled", "-rounded", "-sharp",
    "-alt", "-ios-new", "-ios",
)